### PR TITLE
MNT: Re-rendered with conda-build 3.24.0, conda-smithy 3.23.1, and co…

### PR DESCRIPTION
**Pull request by fabratu**
…nda-forge-pinning 2023.05.31.22.15.24

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fabratu** [comment]
Goal of this is to update `libnetworkit` to use the latest tlx-version. Since tlx is included as a build-requirement, re-rendering the package (resulting in a new build) is the way to go.

**Review by angriman — APPROVED** [review]

**Comment by jaimergp** [comment]
Wrt https://github.com/conda-forge/conda-forge.github.io/issues/1962, I think you need to have `libtlx` in `host`, not `build`.

**Comment by fabratu** [comment]
> Wrt https://github.com/conda-forge/conda-forge.github.io/issues/1962, I think you need to have libtlx in host, not build.

Hm, maybe you are right, and I misunderstood the intention behind `host` and `build` requirements. Will change it.

**Comment by fabratu** [comment]
Hm, since now the builds seem to fail, we need to add a way to let our build-tool (cmake) find TLX in a different location. The folder changed from `<PREFIX>/_build_env` to `<PREFIX>/_h_env_placehold_...`, correct?

**Comment by jaimergp** [comment]
`-DNETWORKIT_EXT_TLX="$CONDA_PREFIX"` should point to `$PREFIX`, I think.

**Comment by fabratu** [comment]
@jaimergp Thx for the help. Everything seems now to work. Will close the referencing issue then.

**Pull request merged**
